name: byte_quiz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"  # Added flutter_launcher_icons package

flutter_icons:
  android: true           # Enable icon generation for Android
  ios: false             # Disable icon generation for iOS (if not needed)
  image_path: "assets/icon/app_icon.png"  # Path to your custom icon

flutter:
  uses-material-design: true
